# 30-mysql.conf — Inserción estructurada en MariaDB
# VM-04 (10.10.20.30) — Ubicación: /etc/rsyslog.d/30-mysql.conf
#
# Carga el módulo ommysql y define la plantilla de inserción.
# Conexión a MariaDB por 127.0.0.1 (NO localhost — fuerza TCP sobre socket Unix).
# Prerequisito: apt install rsyslog-mysql

module(load="ommysql")

template(name="sql-siem" type="list") {
    constant(value="INSERT INTO eventos (fecha, equipo_id, fuente_id, severidad_id, mensaje) VALUES ('")
    property(name="timereported" dateFormat="mysql")
    constant(value="', 1, 1, 2, '")
    property(name="msg" droplastlf="on")
    constant(value="')")
}

*.* action(
    type="ommysql"
    server="127.0.0.1"
    serverport="3306"
    db="siem_logs"
    uid="rsyslog"
    pwd="RsyslogStrongPass2025!"
    template="sql-siem"
)
