# rsyslog-udp.conf — Módulos de recepción remota
# VM-04 (10.10.20.30) — Añadir al inicio de /etc/rsyslog.conf
#
# Habilita la recepción de logs remotos por UDP 514 y TCP 514.
# Prerequisito: apt install rsyslog-mysql (no incluido en Ubuntu 22.04 base)

module(load="imudp")
input(type="imudp" port="514")

module(load="imtcp")
input(type="imtcp" port="514")
